---
title: "hw-01"
author: "Raven Callaghan (S2486713)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
library(readxl)


edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
ex_1_ans_1 <- colSums(is.na(edibnb))
ex_1_ans_1

perfect_reviews <- filter(edibnb, review_scores_rating == 100)
perfect_reviews_arranged <- arrange(perfect_reviews, desc(number_of_reviews))
ex_1_ans_2 <- head(perfect_reviews_arranged, n = 1)
ex_1_ans_2

```


Answer 1: price, neighbourhood, bathrooms, bedrooms, beds, and review_scores_rating are all variables with N/A entries in the dataset.

Answer 2: The ID of the perfect AirBNB with the largest number of reviews is 860170. 

------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}
bnb_oldtown <- filter(edibnb, neighbourhood == "Old Town")
bnb_oldtown_100 <- filter(bnb_oldtown, price > 100)
ex_2_ans_1 <- count(bnb_oldtown_100)
ex_2_ans_1

southside_4ppl <- filter(edibnb, neighbourhood == "Southside" & accommodates >= 4)
ex_2_price <- select(southside_4ppl, price)
min(ex_2_price)

mean(ex_2_price$price, na.rm = TRUE)

max(ex_2_price)
```


Answer 1: There are 494 AirBNB listings in Old Town with a one-night-stay price of more than £100

Answer 2: The minimum price for Southside AirBNB listings that can accommodate 4 people is £10. The mean price for the listings described is £153 to the nearest pound. The maximum price for the listings is £800

------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}
bnb_newington <- filter(edibnb, neighbourhood == "Newington")
bnb_newington_bathrooms <- bnb_newington %>% select(id, neighbourhood, bathrooms)
count(bnb_newington_bathrooms, bathrooms)

bathrooms_adjusted_df <- edibnb %>% mutate("bathrooms_adjusted" = ceiling(bathrooms))
count(bathrooms_adjusted_df, bathrooms, bathrooms_adjusted)

bath_bigger_bed <- filter(bathrooms_adjusted_df, bathrooms_adjusted > bedrooms)
count(bath_bigger_bed)
```

There are 963 total AirBNBs in Edinburgh where the adjusted number of bathrooms is greater than the number of bedrooms. 


------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}
edibnb_council <- left_join(edibnb, council, by = "id")
council_correct_date <- edibnb_council %>% mutate(assessment_date_correct = dmy(assessment_date))
min(council_correct_date$assessment_date_correct)
max(council_correct_date$assessment_date_correct)

#This is to ensure that the range can specifically be defined as May 2022

council_may_list <- council_correct_date %>% filter(between(assessment_date_correct, as.Date('2022-05-01'), as.Date('2022-05-31')))
count(council_may_list)



council_correct_date_assessed <- council_correct_date %>% mutate(assessed = case_when(is.na(assessment_date_correct) ~ "No", TRUE ~ "Yes"))
neighbourhood_assessed <- count(council_correct_date_assessed, neighbourhood, assessed)
neighbourhood_data <- count(edibnb, neighbourhood)
neighbourhood_assessed_data <- left_join(neighbourhood_assessed, neighbourhood_data, by = "neighbourhood")
colnames(neighbourhood_assessed_data) <- c("neighbourhood", "assessed", "count", "total")
neighbourhood_assessed_yes <- filter(neighbourhood_assessed_data, assessed == "Yes")
neighbourhood_assessed_proportion <- neighbourhood_assessed_yes %>% mutate(proportion = count/total)
neighbourhood_barplotdata <- select(neighbourhood_assessed_proportion, neighbourhood, proportion)
                                                                
ggplot(data = neighbourhood_barplotdata) + geom_bar(mapping = aes(x = neighbourhood, y = proportion, fill = neighbourhood),  stat = "identity") + coord_flip()
```


There were 296 inspections by the council in the month of May 2022. 

It is clear from the bar chart that Leith's assessment rate is significantly larger than that of any other borough, suggesting a significant bias toward properties in this neighbourhood.


------------------------------------------------------------------------------
